### ISSUE TITLE
Error 'DeviceCapability' has no attribute 'OFF_LIMITS' after update

### ISSUE THREAD

**Issue by stskrp** [MTrab/landroid_cloud#857]
### Describe the issue

Hello,
I'm after update to 5.2.2 version (previously it was on 5.1.0), I'm getting error when restarting HA, and worx integration is unavailable

![Image](https://github.com/user-attachments/assets/3a8ba9a2-9362-4f1b-a65e-820ce5135715)

### What version of Home Assistant Core has the issue?

2025.4.3

### What version of the Landroid Cloud integration do you have installed

5.2.2

### What type of installation are you running?

Home Assistant Container

### Which make and model is the mower used for this integration?

Landroid M500 (WR165E)

### Diagnostics information (NOT log entries!)

Not able to download it, getting error "file not available on server"

### Relevant log entries

```txt
2025-04-22 09:16:41.898 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1052, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/landroid_cloud/__init__.py", line 14, in <module>
    from .api import LandroidAPI
  File "/config/custom_components/landroid_cloud/api.py", line 18, in <module>
    from .const import (
    ...<5 lines>...
    )
  File "/config/custom_components/landroid_cloud/const.py", line 348, in <module>
    DeviceCapability.OFF_LIMITS: LandroidFeatureSupport.OFFLIMITS,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'DeviceCapability' has no attribute 'OFF_LIMITS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 992, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1063, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.landroid_cloud

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1052, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/landroid_cloud/__init__.py", line 14, in <module>
    from .api import LandroidAPI
  File "/config/custom_components/landroid_cloud/api.py", line 18, in <module>
    from .const import (
    ...<5 lines>...
    )
  File "/config/custom_components/landroid_cloud/const.py", line 348, in <module>
    DeviceCapability.OFF_LIMITS: LandroidFeatureSupport.OFFLIMITS,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'DeviceCapability' has no attribute 'OFF_LIMITS'
2025-04-22 09:16:41.918 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'landroid_cloud': Unable to import component: Exception importing custom_components.landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1052, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/landroid_cloud/__init__.py", line 14, in <module>
    from .api import LandroidAPI
  File "/config/custom_components/landroid_cloud/api.py", line 18, in <module>
    from .const import (
    ...<5 lines>...
    )
  File "/config/custom_components/landroid_cloud/const.py", line 348, in <module>
    DeviceCapability.OFF_LIMITS: LandroidFeatureSupport.OFFLIMITS,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'DeviceCapability' has no attribute 'OFF_LIMITS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 992, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1063, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.landroid_cloud

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1052, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/landroid_cloud/__init__.py", line 14, in <module>
    from .api import LandroidAPI
  File "/config/custom_components/landroid_cloud/api.py", line 18, in <module>
    from .const import (
    ...<5 lines>...
    )
  File "/config/custom_components/landroid_cloud/const.py", line 348, in <module>
    DeviceCapability.OFF_LIMITS: LandroidFeatureSupport.OFFLIMITS,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'DeviceCapability' has no attribute 'OFF_LIMITS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 340, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1012, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1004, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1063, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.landroid_cloud
```

**Comment by stskrp** [comment]
OFF limits module is installed on mower

![Image](https://github.com/user-attachments/assets/69f710b7-062d-4aed-b69d-0c8fbc33b6e0)

![Image](https://github.com/user-attachments/assets/6a6c04b2-71d1-4334-a152-c71286d0f2b3)

**Comment by MTrab** [comment]
Please try reinstalling the integration- seems like some files haven't been updated correctly

**Comment by stskrp** [comment]
Reinstalling didn't help :/
tried uninstall/install custom_component (with HA restarts)
tried also manually cleaning up custom_components/landroid_cloud
But still getting same issue
