### ISSUE TITLE
setzone stopped working after upgrade

### ISSUE THREAD

**Issue by sbias** [MTrab/landroid_cloud#177]
After upgrading to v2.1.2 the setzone call fails.

This is how i call the service:
```
service: landroid_cloud.setzone
data:
  zone: '2'
target:
  entity_id: vacuum.rasimir
```

This is what appears in HA logfile:
```
2022-06-30 11:29:02 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'DeviceHandler' object has no attribute 'zone_probability'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/home/homeassistant/.homeassistant/custom_components/landroid_cloud/services.py", line 155, in async_call_landroid_service
    await api.services[service][ATTR_SERVICE](service_data)
  File "/home/homeassistant/.homeassistant/custom_components/landroid_cloud/device_base.py", line 677, in async_set_zone
    await self.hass.async_add_executor_job(partial(device.setzone, str(zone)))
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/pyworxcloud/utils/actions.py", line 186, in setzone
    current = self.zone_probability
AttributeError: 'DeviceHandler' object has no attribute 'zone_probability'
2022-06-30 11:29:02 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1550688512] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/commands.py", line 636, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/home/homeassistant/.homeassistant/custom_components/landroid_cloud/services.py", line 155, in async_call_landroid_service
    await api.services[service][ATTR_SERVICE](service_data)
  File "/home/homeassistant/.homeassistant/custom_components/landroid_cloud/device_base.py", line 677, in async_set_zone
    await self.hass.async_add_executor_job(partial(device.setzone, str(zone)))
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/pyworxcloud/utils/actions.py", line 186, in setzone
    current = self.zone_probability
AttributeError: 'DeviceHandler' object has no attribute 'zone_probability'
```
