### ISSUE TITLE
'WorxCloud' object has no attribute 'partymode'

### ISSUE THREAD

**Issue by maury77** [MTrab/landroid_cloud#88]
After upgrade to 2021.12.4 

The componente have some problem

Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.7/lib/python3.9/site-packages/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/mnt/dietpi_userdata/homeassistant/custom_components/landroid_cloud/__init__.py", line 154, in async_setup
    _LOGGER.debug("Partymode available: %s", client[dev].partymode)
AttributeError: 'WorxCloud' object has no attribute 'partymode'

**Comment by MTrab** [comment]
Turn on the mower - at the moment there is an issue when the mower is offline.

**Comment by doudz** [comment]
Same bug for me, not really a problem but I can't turn on the mower since it's winter and the mower is in the garage ;)

**Comment by Waling1961** [comment]
Here also the same problem after update  2021.12.4

Logger: homeassistant.setup
Source: custom_components/landroid_cloud/__init__.py:154
Integration: landroid_cloud (documentation, issues)
First occurred: 20:32:32 (1 occurrences)
Last logged: 20:32:32

Error during setup of component landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/landroid_cloud/__init__.py", line 154, in async_setup
    _LOGGER.debug("Partymode available: %s", client[dev].partymode)
AttributeError: 'WorxCloud' object has no attribute 'partymode'

**Comment by MTrab** [comment]
The integration are getting a complete overhaul during the winter season - then this will be fixed along with a few other minor bugs.

**Comment by MTrab** [comment]
Duplicate of #86

**Comment by CubieMedia** [comment]
Same issue here, will not turn on mower until spring. If you need someone to test a new version i am willing to help on short notice.

**Comment by MTrab** [comment]
Fixed in v1.8.1
