### ISSUE TITLE
Integration v4.0.0b3 fails to start 

### ISSUE THREAD

**Issue by spockster1985** [MTrab/landroid_cloud#473]
### Describe the issue

Updated from v4.0.0b1 to v4.0.0b3. v4.0.0b1 is working, but after update to v4.0.0b3 it will not load the integration.

### What version of Home Assistant Core has the issue?

core-2023.9.3

### What version of the Landroid Cloud integration do you have installed

v4.0.0b3

### What type of installation are you running?

Home Assistant Container

### Which make and model is the mower used for this integration?

Worx Landroid S500i

### Diagnostics information (NOT log entries!)

None

### Relevant log entries

```txt
2023-11-16 20:34:03.968 ERROR (MainThread) [homeassistant.components.lawn_mower] Error adding entities for domain lawn_mower with platform landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 616, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial_number'
2023-11-16 20:34:03.979 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 616, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial_number'
```

**Comment by ndanzi** [comment]
Same for me

**Comment by MTrab** [comment]
Would it be possible to lend access to one of your accounts to debug on this?
I cannot recreate with any of the ones I already have access to at the moment.

Credentials can be sent by email to landroid_cloud (at) trab.dk
